config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tube.urls"), name="tube"),
    path('accounts/',include("allauth.urls"),name="account"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tube/urls.py
from django.urls import path
from . import views


app_name = "tube"
urlpatterns =[
    path('', views.index, name="index"),

    # TIPS:<型:変数名>とすることでビューに変数を与えることができる
    #idをuuidにするので、intをuuidに変える。

    path('delete/<uuid:video_pk>/', views.delete, name="delete"),
    path('update/<uuid:video_pk>/', views.update, name="update"),
    path('single/<uuid:video_pk>/', views.single, name="single"),
    ]

tube/models.py
from django.db import models
from django.utils import timezone

import uuid


class Category(models.Model):

    class Meta:
        db_table = "category"

    # TIPS:数値型の主キーではPostgreSQLなど一部のDBでエラーを起こす。それだけでなく予測がされやすく衝突しやすいので、UUID型の主キーに仕立てる。
    id     = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False )
    name   = models.CharField(verbose_name="カテゴリ名", max_length=20)

    def __str__(self):
        return self.name

#実際には動画サイトで多対多を実装する時、良いね悪いねの評価等に使う。タグはハッシュタグとして扱うほうがよい。
class Tag(models.Model):

    class Meta:
        db_table = "tag"

    id     = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False )
    name   = models.CharField(verbose_name="タグ名", max_length=20)

    def __str__(self):
        return self.name


class Video(models.Model):

    class Meta:

        db_table = "video"

    id       = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False )
    title    = models.CharField(verbose_name="タイトル", max_length=50)

    category = models.ForeignKey(Category, verbose_name="カテゴリ", on_delete=models.PROTECT)

    tag      = models.ManyToManyField(Tag, verbose_name="タグ", blank=True)

    description  = models.CharField(verbose_name="動画説明文", max_length=300)
    dt           = models.DateTimeField(verbose_name="投稿日", default=timezone.now)
    edited       = models.BooleanField(default=False)

    image        = models.ImageField(verbose_name="画像",upload_to="tube/image",blank=True)
    movie        = models.FileField(verbose_name="動画",upload_to="tube/movie",blank=True)

    def __str__(self):
        return self.title


class VideoComment(models.Model):

    class Meta:
        db_table = "comment"

    id      = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False )
    content = models.CharField(verbose_name="コメント文", max_length=500)
    target  = models.ForeignKey(Video, verbose_name="コメント先の動画", on_delete=models.CASCADE)
    dt      = models.DateTimeField(verbose_name="投稿日", default=timezone.now)

    def __str__(self):
        return self.content


tube/forms.py
from django import forms
from .models import Video,VideoComment

class VideoForm(forms.ModelForm):
    class Meta:
        model  = Video
        fields = ["title", "description", "image", "movie", "category", "tag",]

class VideoEditForm(forms.ModelForm):
    class Meta:
        model  = Video
        fields = ["title", "description", "dt",]

class VideoCommentForm(forms.ModelForm):
    class Meta:
        model  = VideoComment
        fields = [ "content", "target", ] #←フォームにないdtがあると常にバリデーションエラーになってしまう。

"""
class VideoCommentForm(forms.ModelForm):
    class Meta:
        model  = VideoComment
        fields = ["content", "target", "dt",]

    class Meta2:
        model  = Video
        fields = ["title", "description", "image", "movie", "category", "tag", ]
"""

tube/views.py
from rest_framework import status,views,response
from django.shortcuts import render, redirect

from django.views import View
from django.db.models import Q

from django.http.response import JsonResponse
from django.template.loader import render_to_string


#ページネーション
from django.core.paginator import Paginator 



#TIPS:Djangoの中に含まれるクラスなどは↑へ、models.py,forms.pyなどの自分で作ったクラスを↓へ配置すると見やすい

from .models import Video,Category,Tag,VideoComment
from .forms import VideoForm, VideoEditForm,VideoCommentForm
from .serializer import VideoSerializer,VideoCommentSerializer



#python-magicで受け取ったファイルのMIMEをチェックする。
#MIMEについては https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types を参照。

import magic
ALLOWED_MIME   = ["video/mp4"]

# アップロードの上限
LIMIT_SIZE     = 200 * 1000 * 1000

class IndexView(View):

    def get(self, request, *args, **kwargs):

        categories = Category.objects.all()
        tags       = Tag.objects.all()

        if "search" in request.GET:

            if request.GET["search"] == "" or request.GET["search"].isspace():
                return redirect("tube:index")


            search = request.GET["search"].replace("　", " ")
            search_list = search.split(" ")


            query = Q()
            for word in search_list:

                if "option" in request.GET:
                    query |= Q(description__contains=word)
                else:
                    query &= Q(description__contains=word)

            videos = Video.objects.filter(query).order_by("-dt")
        else:
            videos = Video.objects.all().order_by("-dt")


        #===========ここからページネーション処理================
        paginator   = Paginator(videos,3) #←(ページネーション化させたいデータ、1ページに表示させる数)

        if "page" in request.GET:
            videos    = paginator.get_page(request.GET["page"])
        else:
            videos    = paginator.get_page(1)




        context = {"videos": videos,
                   "categories":categories,
                   "tags":tags,
                   }


        return render(request, "tube/index.html", context)

    def post(self, request, *args, **kwargs):

        # TIPS:request.POSTだけでなく、request.FILESも引数に入れる。
        formset = VideoForm(request.POST, request.FILES)

        fileflag  = False


        if "movie" in request.FILES:
            mime_type  = magic.from_buffer(request.FILES["movie"].read(1024),mime=True)

            if request.FILES["movie"].size >= LIMIT_SIZE:

                mb     = str(LIMIT_SIZE / 1000000)

                json= { "error":True,
                        "message":"The maximum file size is " + mb + "MB"}

                return JsonResponse(json)

            if mime_type not in ALLOWED_MIME:

                mime   = str(ALLOWED_MIME)
                json   = { "error":True,
                           "message":"The file you can post is " + mime + "." }

                return JsonResponse(json)

            if mime_type in ALLOWED_MIME:
                fileflag  = True

        else:
            fileflag  = True

        # ↑アップロードされたファイルが許可されているMIMEである、もしくはアップロードされていない場合。リクエストの保存を許可する。

        if formset.is_valid():
            print("バリデーションOK")

            if fileflag:
                formset.save()
            else:
                print("このファイルは許可されていません。")

        else:
            print("バリデーションエラー")


        return redirect("tube:index")

index = IndexView.as_view()


class SingleView(View):

    def get(self,request, video_pk, *args, **kwargs):

        video = Video.objects.filter(id=video_pk).first()

        comments = VideoComment.objects.filter(target=video_pk).order_by("-dt")

        context = {"video": video,
                   "comments": comments,
                   }

        return render(request, "tube/single.html", context)


    def post(self, request, video_pk, *args, **kwargs):

        #Formクラスを使ったバリデーション
        copied              = request.POST.copy()
        copied["target"]    = video_pk

        form    = VideoCommentForm(copied)
        if form.is_valid():
            print("コメントバリデーションOK")
            form.save()
        else:
            print("コメントバリデーションNG")


        """
        serializer  = VideoCommentSerializer(data=copied)

        if serializer.is_valid():
            print("コメントバリデーションOK")
            serializer.save()
        else:
            print("コメントバリデーションNG")

        """
        return redirect("tube:single", video_pk=video_pk)


single = SingleView.as_view()


class DeleteView(View):

    def get(self, request, video_pk, *args, **kwargs):

        video   = Video.objects.filter(id=video_pk).first()
        context = { "video":video }

        return render(request, "tube/delete.html", context )


    def post(self, request, video_pk, *args, **kwargs):

        print("削除")

        # .first()で一番上のレコードを1つ取る。
        video    = Video.objects.filter(id=video_pk).first()
        video.delete()

        # TIPS:すでにurls.pyにてpkが数値型であることがわかっているので、バリデーションをする必要はない。

        return redirect("tube:index")

delete = DeleteView.as_view()


class UpdateView(View):

    def get(self, request, video_pk, *args, **kwargs):

        video   = Video.objects.filter(id=video_pk).first()
        context = { "video":video }

        return render(request, "tube/update.html", context )

    def post(self, request, video_pk, *args, **kwargs):

        # まず、編集対象のレコード特定
        instance    = Video.objects.filter(id=video_pk).first()

        # 第2引数にinstanceを指定することで、対象の編集ができる。
        formset     = VideoEditForm(request.POST, instance=instance)

        if formset.is_valid():
            print("バリデーションOK")
            formset.save()
            Video.objects.filter(id=video_pk).update(edited=True)

        else:
            print("バリデーションNG")

        return redirect("tube:index")


update  = UpdateView.as_view()

templates/tube/delete.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
         <title>削除ページ</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <style>
        h2 {
           color: red;
           font-weight: bold;
           }
    </style>
</head>

<body>
    <h2>Worning!</h2>
    <div>
        <p>一度削除すると、元に戻すことが出来ません。本当に削除しますか？</p>
    </div>

          <form action="{% url 'tube:delete' video.id %}" method ="POST" style="display:inline-block;">
            {% csrf_token %}
            <button class="btn btn-danger">Yes</button>
          </form>

           <a class="btn btn-success" href="{% url 'tube:index' %}">No</a>


</body>
</html>

templates/tube/index.html
{% extends "common/sidebar.html" %}
{% load static %}
{% load param_change %} {# ←ページネーション用のカスタムテンプレートタグを読み込む #}



{% block site_title %}サイトのタイトル{% endblock %}


{% block extra_head %}
<script>console.log("追加のcssやjsがあればここにまとめて書く");</script>

{% endblock %}



{% block page_title %}{% endblock %}

{% block main %}
<main class="container">

        <form method="GET">
            <div>OR検索はチェックを入れる:<input type="checkbox" name="option" {% if request.GET.option %}checked{% endif %}></div>
            <input type="text" name="search" value="{{ request.GET.search }}">
            <input type="submit" value="検索">
        </form>


        <!--TIPS:ファイルをアップロードする場合、 enctype="multipart/form-data" をformタグに入れる。-->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div>
                <select name="category">
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div>
                {% for tag in tags %}
                <input id ="{{ tag.id }}" type="checkbox" name="tag" value="{{ tag.id }}"><label for="{{ tag.id }}">{{ tag.name }}</label>
                {% endfor %}
            </div>

            <div><input class = "form-text" placeholder="タイトル..." name="title" value="{{ request.POST.title }}"></div>

            <div><textarea class="form-control" name="description" placeholder="概要欄...">{{ video.description }}</textarea></div>

            <div>画像：<input type="file" accept=".jpg,.png" name="image"></div>
            <div>動画：<input type="file" accept="video/mp4" name="movie"></div>

            <div>
                <ul>
                    <li>mp4ファイルのみ対応しています。</li>
                    <li>ファイルサイズは上限200MBです。</li>
                 </ul>
            </div>

            <input class="form-control my-2" type="submit" value="送信">

        </form>

        {% for video in videos %}

           <div class="video_content_list">
               <div class="video_content">
                    <a class="video_content_link" href="{% url 'tube:single' video.id %}">
                        {% if video.image %}<div><img src="/media/{{ video.image }}" alt="投稿された画像"></div>{% endif %}
                        {% if video.movie %}<div><video src="/media/{{ video.movie }}" alt="投稿された動画" controls></video></div>{% endif %}
                        <div>タイトル ：{{ video.title }}</div>
                    </a>
               </div>
           </div>


           <div class="border">

             {% if video.edited %}
                <p class="sort">Edited</p>
             {% endif %}

             <div>
                 {% if video.edited %}更新日 ：{{ video.dt }}
                 {% else %}投稿日 ：{{ video.dt }}
                 {% endif %}
             </div>

             <div>カテゴリ :{{ video.category.name }}</div>

             <!--TIPS:複数選択されたタグを全て表示させる時はこのようにする。-->
             <div>タグ :{% for tag in video.tag.all %}{{ tag }} {% endfor %}</div>

             <div>{{ video.description }}</div>

             <div>
                 <a class="btn btn-outline-info" href="{% url 'tube:single' video.id %}">コメントする</a>
             </div>

             <a class="btn btn-danger" href="{% url 'tube:delete' video.id %}">削除</a>
             <a class="btn btn-success" href="{% url 'tube:update' video.id %}">編集</a>

           </div>
       {% endfor %}


        <!-- 検索とページが両立しない場合 ここから -->
        <ul class="pagination justify-content-center">
            {% if videos.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">最初のページ</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ videos.previous_page_number }}">前のページ</a></li>
            {% else %}
            <li class="page-item"><a class="page-link">最初のページ</a></li>
            <li class="page-item"><a class="page-link">前のページ</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link">{{ videos.number }}</a></li>
            {% if videos.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ videos.next_page_number }}">次のページ</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ videos.paginator.num_pages }}">最後のページ</a></li>
            {% else %}
            <li class="page-item"><a class="page-link">次のページ</a></li>
            <li class="page-item"><a class="page-link">最後のページ</a></li>
            {% endif %}
        </ul>
        <!-- 検索とページが両立しない場合 ここまで -->


        {{ request.GET }}

        <!-- 検索とページが両立する場合 ここから -->
        <ul class="pagination justify-content-center">
            {% if videos.has_previous %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' '1' %}">最初のページ</a></li>
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' videos.previous_page_number %}">前のページ</a></li>
            {% else %}
            <li class="page-item"><a class="page-link">最初のページ</a></li>
            <li class="page-item"><a class="page-link">前のページ</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link">{{ videos.number }}</a></li>
            {% if videos.has_next %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' videos.next_page_number %}">次のページ</a></li>
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' videos.paginator.num_pages %}">最後のページ</a></li>
            {% else %}
            <li class="page-item"><a class="page-link">次のページ</a></li>
            <li class="page-item"><a class="page-link">最後のページ</a></li>
            {% endif %}
        </ul>
        <!-- 検索とページが両立する場合 ここまで -->



</main>
{% endblock %}





{# ユーザーがログイン済みの場合、userのis_authenticated属性値で判定できる。 #}
  {#% if user.is_authenticated %#}
 {# <div>こんにちは{{ user.get_username }}さん</div> #}
  {#% else %#}
  {# <div>ログインしてください</div> #}
  {#% endif %#}



templates/tube/single.html
{% extends "common/sidebar.html" %}


{% block site_title %}個別ページ{% endblock %}


{% block extra_head %}
<script>console.log("追加のcssやjsがあればここにまとめて書く");</script>
<style>
    .sort {
       float: right;
       margin-right: 30%;
       font-weight: bold;
       color: chartreuse;
    }
</style>
{% endblock %}



{% block page_title %}{% endblock %}

{% block main %}
     <main class="container">

         {% if video.image %}<div><img src="/media/{{ video.image }}" alt="投稿された画像"></div>{% endif %}
         {% if video.movie %}<div><video src="/media/{{ video.movie }}" alt="投稿された動画" controls></video></div>{% endif %}

         <div class="border">
            {# <div>{{ video.id }}</div> #}

            {% if video.edited %}
               <p class="sort">Edited</p>
            {% endif %}

            <div>タイトル ：{{ video.title }}</div>

            <div>
                {% if video.edited %}更新日 ：{{ video.dt }}
                {% else %}投稿日 ：{{ video.dt }}
                {% endif %}
            </div>

            <div>カテゴリ :{{ video.category.name }}</div>

            <div>タグ :{% for tag in video.tag.all %}{{ tag }} {% endfor %}</div>

            <div>{{ video.description }}</div>

            <div>
              <form action="{% url 'tube:single' video.id %}" method="POST" >
                {% csrf_token %}
                <div><textarea class="form-control" name="content" placeholder="コメント...">{{ comment.content }}</textarea></div>

                <button class="btn btn-outline-primary" >投稿</button>


              </form>
              <a class="btn btn-outline-dark" type="reset" href="{% url 'tube:single' video.id %}" >キャンセル</a>
              <a class="btn btn-outline-success" href="{% url 'tube:index' %}">検索ページへ</a>
            </div>

            {% if comments %}

                 {% for comment in comments %}
                   <div class="border">{{ comment.content }}</div>
                 {% endfor %}
            {% else %}
                    <div>コメントはまだありません。</div>
            {% endif %}

         </div>
     </main>
{% endblock %}

templates/tube/update.html
<!DOCTYPE html>
<html lang="ja">
<head>
         <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
         <title>編集</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


</head>
<body>

    <form method="POST">
        {% csrf_token %}

        <div><input class="form-text" placeholder="タイトル..." name="title" value="{{ video.title }}"></div>
        <!--TIPS:textarea属性にvalue属性は存在しない、中のタグに値を入れる。-->
        <div><textarea class="form-control" name="description" placeholder="概要欄...">{{ video.description }}</textarea></div>
        <div><input class="form-text" placeholder="更新日..." name="dt" value="{{ video.dt|date:'Y-m-d H:i' }}"></div>

        <input type="submit" value="送信">

    </form>

</body>
</html>